GET http://localhost:5001/myFirstGet

###
POST http://localhost:5001/register/create
content-type: application/json

{
    "fname": "sampleFirstName",
    "lname": "sampleLastName",
    "email": "email@gmail.com",
    "password": "samplePassword"
}
